version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:5.7
    container_name: oilpier-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: oil_pier_harbour
      MYSQL_USER: oilpier
      MYSQL_PASSWORD: oilpier123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - oilpier-network

  # Redis缓存
  redis:
    image: redis:6-alpine
    container_name: oilpier-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - oilpier-network

  # RabbitMQ消息队列
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: oilpier-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - oilpier-network

  # MQTT Broker
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: oilpier-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - oilpier-network

  # MinIO对象存储
  minio:
    image: minio/minio:latest
    container_name: oilpier-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - oilpier-network

  # 后端应用
  backend:
    build: .
    container_name: oilpier-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/oil_pier_harbour?useUnicode=true&characterEncoding=utf8&useSSL=false
      SPRING_DATASOURCE_USERNAME: oilpier
      SPRING_DATASOURCE_PASSWORD: oilpier123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      OILPIER_MQTT_BROKER: tcp://mqtt:1883
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - mqtt
    networks:
      - oilpier-network

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: oilpier-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - oilpier-network

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
  minio_data:

networks:
  oilpier-network:
    driver: bridge
